// app/page.tsx
import Hero from "@/components/hero"
import About from "@/components/about"
import Skills from "@/components/skills"
import Projects from "@/components/projects"
import Contact from "@/components/contact"

export default function Home() {
  return (
    <>
      <Hero />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </>
  )
}

// src/src/App.vue
<script setup>
import HomeView from './views/Home.vue';
import AboutView from './views/About.vue';
import ProjectsView from './views/Projects.vue';
import SkillsView from './views/Skills.vue';
import ContactView from './views/Contact.vue';
import FooterView from './views/Footer.vue';
</script>

<template>
    <div class="container">
        <HomeView />


        <AboutView />


        <ProjectsView />


        <SkillsView />


        <ContactView />

        <FooterView />

    </div>
</template>
